markdown: rdiscount
pygments: true
permalink: /:month/:year/:title

home_url: http://joehand.org
blog_url: http://happy.smilingjoe.com
about_url: http://happy.smilingjoe.com/about.html

jspath: http://happy.smilingjoe.com/assets/js
csspath: http://happy.smilingjoe.com/assets/css
imgpath: http://happy.smilingjoe.com/assets/img

name: "Smiling Joe"
author: "Joe Hand"

disqus_shortname: "smilingjoe"
google_analytics_ID: "UA-20883592-3"

main_color: "1C90C1"
main_color_rgb: "28,144,193"
highlight_color: "7CC9CF"
highlight_color_rgb: "124,201,207"
background_color: "BEE2E7"
background_color_rgb: "190,226,231"
dark_color: "696969"
dark_color_rgb: "105,105,105"
extra_color: "CD4C39"
extra_color_rgb: "205,76,57"

auto: true
rdiscount:
  extensions: [smart]
