markdown: rdiscount
pygments: true
permalink: /:month/:year/:title

home_url: http://joehand.org
blog_url: http://smilingjoe.com
about_url: http://smilingjoe.com/about.html
support_url: http://smilingjoe.com/support.html
cookie_url: http://smilingjoe.com/cookie.html
updates_url: http://smilingjoe.com/updates.html
#home_url: /
#home_url: /
#blog_url: /
jspath: http://smilingjoe.com/assets/js/
csspath: http://smilingjoe.com/assets/css/
imgpath: http://smilingjoe.com/assets/img/

name: "Smiling Joe"
description: "Experiments in kindness."


auto: true
rdiscount:
  extensions: [smart]
