markdown: rdiscount
pygments: true
permalink: /:month/:year/:title

home_url: http://joehand.org
blog_url: http://smilingjoe.com
about_url: http://smilingjoe.com/about.html
#home_url: /
#home_url: /
#blog_url: /

name: "Smiling Joe"
root_desc: "SmilingJoe.com"
description: "Experiments in random acts of kindness."

auto: true
rdiscount:
  extensions: [smart]