markdown: rdiscount
pygments: true
permalink: /:month/:year/:title

home_url: http://localhost/joe/
blog_url: http://localhost/blog/
#home_url: /
#blog_url: /

root_desc: "JoeHand.org"
description: "A blog from Joe Hand."

auto: true
rdiscount:
  extensions: [smart]